### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by llvll0hsen** [lewkoo/dashvis#4]
hey I am trying to build library but I receive the following error after using `npm run build` 

```
spaces\git_repos\dashvis> npm run build

> dashvis@0.1.3 build
> npm run build:js && npm run build:backends


> dashvis@0.1.3 build:js
> webpack --mode production

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\webpack\lib\util\createHash.js:135:53)        
    at NormalModule._initBuildHash (C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at context.callback (C:\Users\M\Dokumente\Workspaces\git_repos\dashvis\node_modules\loader-runner\lib\LoaderRunner.js:111:13)   
    at C:\UsersM\Dokumente\Workspaces\git_repos\dashvis\node_modules\babel-loader\lib\index.js:44:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],  
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
I use `Node.js v18.16.0` and `Dash 2.9.3 ` . I tried updating the npm, after removing the `node_modules` but it didn't work. do you have any idea what could be the problem?

**Comment by lewkoo** [comment]
Hi @llvll0hsen,

I also got this error on `Node.js v18.15.0`. I solved it with an update. Please pull the updates and try again.
